import type { PackageCatalogEntry } from "./types.js";

function entry(config: PackageCatalogEntry): PackageCatalogEntry {
  return config;
}

/** Authoritative catalog of every public toolkit package. */
export const PACKAGE_CATALOG: readonly PackageCatalogEntry[] = [
  entry({
    id: "core",
    title: "Core",
    npmPackage: "@ailuracode/alpine-core",
    folder: "core",
    category: "runtime-composition",
    role: "foundation",
    surface: "core",
    api: "registerPlugin · initPlugins",
    summary:
      "Lightweight plugin registry and lifecycle orchestration for Alpine.js toolkit packages.",
    readmePath: "packages/core/README.md",
    tier: "essential",
    order: 1,
    badges: ["infrastructure"],
    docs: { available: true, routeId: "core" },
  }),
  entry({
    id: "overlay",
    title: "Overlay",
    npmPackage: "@ailuracode/alpine-overlay",
    folder: "overlay",
    category: "runtime-composition",
    role: "foundation",
    surface: "store",
    api: "$store.overlay / $overlay",
    summary:
      "Portal root, z-index stack, and overlay registry used by dialog, menu, tooltip, and command.",
    readmePath: "packages/overlay/README.md",
    tier: "essential",
    order: 2,
    badges: ["infrastructure"],
    related: ["dialog", "menu", "tooltip", "command"],
    demo: { available: true, componentId: "overlay" },
    docs: { available: false },
  }),
  entry({
    id: "keyboard",
    title: "Keyboard",
    npmPackage: "@ailuracode/alpine-keyboard",
    folder: "keyboard",
    category: "runtime-composition",
    role: "foundation",
    surface: "store",
    api: "$store.keyboard / $keyboard",
    summary: "Scoped keyboard shortcut registry with chords, sequences, and conflict resolution.",
    readmePath: "packages/keyboard/README.md",
    tier: "essential",
    order: 3,
    badges: ["infrastructure"],
    demo: { available: true, componentId: "keyboard" },
    docs: { available: true },
  }),
  entry({
    id: "child",
    title: "Child",
    npmPackage: "@ailuracode/alpine-child",
    folder: "child",
    category: "runtime-composition",
    role: "feature",
    surface: "directive",
    api: "x-child",
    summary: "asChild-style directive that merges wrapper attributes onto the first child.",
    readmePath: "packages/child/README.md",
    tier: "extended",
    order: 4,
    requires: ["@alpinejs/morph"],
    demo: { available: true, componentId: "child" },
    docs: { available: true },
  }),
  entry({
    id: "toggle",
    title: "Toggle",
    npmPackage: "@ailuracode/alpine-toggle",
    folder: "toggle",
    category: "interaction-primitives",
    role: "feature",
    surface: "magic",
    api: "$toggle",
    summary: "Binary and ternary toggle state factories for segmented controls and filters.",
    readmePath: "packages/toggle/README.md",
    tier: "extended",
    order: 1,
    related: ["theme"],
    demo: { available: true, componentId: "toggle" },
    docs: { available: true },
  }),
  entry({
    id: "theme",
    title: "Theme",
    npmPackage: "@ailuracode/alpine-theme",
    folder: "theme",
    category: "application-shell",
    role: "feature",
    surface: "store",
    api: "$store.theme",
    summary: "Light, dark, and system color modes with persistence and pluggable DOM strategies.",
    readmePath: "packages/theme/README.md",
    tier: "essential",
    order: 1,
    badges: ["recommended"],
    related: ["toggle"],
    demo: { available: true, componentId: "theme" },
    docs: { available: true },
  }),
  entry({
    id: "media",
    title: "Media",
    npmPackage: "@ailuracode/alpine-media",
    folder: "media",
    category: "application-shell",
    role: "feature",
    surface: "store",
    api: "$store.media",
    summary: "Reactive viewport breakpoints, dimensions, and browser media features.",
    readmePath: "packages/media/README.md",
    tier: "essential",
    order: 2,
    related: ["sidebar"],
    demo: { available: true, componentId: "media" },
    docs: { available: true },
  }),
  entry({
    id: "scroll",
    title: "Scroll",
    npmPackage: "@ailuracode/alpine-scroll",
    folder: "scroll",
    category: "application-shell",
    role: "feature",
    surface: "store",
    api: "$store.scroll / $scroll",
    summary: "Scroll position tracking, section observer, and handle-based body lock.",
    readmePath: "packages/scroll/README.md",
    tier: "essential",
    order: 3,
    demo: { available: true, componentId: "scroll" },
    docs: { available: true },
  }),
  entry({
    id: "sidebar",
    title: "Sidebar",
    npmPackage: "@ailuracode/alpine-sidebar",
    folder: "sidebar",
    category: "application-shell",
    role: "feature",
    surface: "store",
    api: "$store.sidebar",
    summary: "Open, close, and toggle visibility for application shells.",
    readmePath: "packages/sidebar/README.md",
    tier: "essential",
    order: 4,
    related: ["media", "scroll"],
    demo: { available: true, componentId: "sidebar" },
    docs: { available: true },
  }),
  entry({
    id: "lang",
    title: "Lang",
    npmPackage: "@ailuracode/alpine-lang",
    folder: "lang",
    category: "application-shell",
    role: "feature",
    surface: "store",
    api: "$store.lang",
    summary: "Detect, query, and change the current application language.",
    readmePath: "packages/lang/README.md",
    tier: "essential",
    order: 5,
    demo: { available: true, componentId: "lang" },
    docs: { available: true },
  }),
  entry({
    id: "permissions",
    title: "Permissions",
    npmPackage: "@ailuracode/alpine-permissions",
    folder: "permissions",
    category: "browser-capabilities",
    family: "permissions",
    role: "foundation",
    surface: "store",
    api: "$store.permissions / $permissions",
    summary: "Unified browser permission registry with a typed adapter contract.",
    readmePath: "packages/permissions/README.md",
    tier: "essential",
    order: 1,
    badges: ["infrastructure"],
    related: ["notify", "geo", "attention"],
    demo: { available: true, componentId: "permissions" },
    docs: { available: true },
  }),
  entry({
    id: "env",
    title: "Env",
    npmPackage: "@ailuracode/alpine-env",
    folder: "env",
    category: "browser-capabilities",
    role: "capability",
    surface: "magic",
    api: "$network · $visibility · $battery · $platform",
    summary: "Browser environment magics and optional headless environment controller.",
    readmePath: "packages/env/README.md",
    tier: "extended",
    order: 2,
    badges: ["browser-only"],
    demo: { available: true, componentId: "env" },
    docs: { available: true },
  }),
  entry({
    id: "transfer",
    title: "Transfer",
    npmPackage: "@ailuracode/alpine-transfer",
    folder: "transfer",
    category: "browser-capabilities",
    role: "capability",
    surface: "magic",
    api: "$clipboard · $share · $export",
    summary: "Clipboard copy, Web Share API, and programmatic downloads.",
    readmePath: "packages/transfer/README.md",
    tier: "extended",
    order: 3,
    badges: ["browser-only"],
    demo: { available: true, componentId: "transfer" },
    docs: { available: true },
  }),
  entry({
    id: "notify",
    title: "Notify",
    npmPackage: "@ailuracode/alpine-notify",
    folder: "notify",
    category: "browser-capabilities",
    family: "permissions",
    role: "capability",
    surface: "magic",
    api: "$notify",
    summary: "Browser notifications and push permission helpers.",
    readmePath: "packages/notify/README.md",
    tier: "advanced",
    order: 4,
    badges: ["browser-only"],
    related: ["permissions", "toast"],
    requires: ["permissions"],
    demo: { available: true, componentId: "notify" },
    docs: { available: true },
  }),
  entry({
    id: "geo",
    title: "Geo",
    npmPackage: "@ailuracode/alpine-geo",
    folder: "geo",
    category: "browser-capabilities",
    family: "permissions",
    role: "capability",
    surface: "store",
    api: "$store.geo",
    summary: "Geolocation coordinates, accuracy, and permission state.",
    readmePath: "packages/geo/README.md",
    tier: "advanced",
    order: 5,
    badges: ["browser-only"],
    related: ["permissions"],
    requires: ["permissions"],
    demo: { available: true, componentId: "geo" },
    docs: { available: true },
  }),
  entry({
    id: "attention",
    title: "Attention",
    npmPackage: "@ailuracode/alpine-attention",
    folder: "attention",
    category: "browser-capabilities",
    family: "permissions",
    role: "capability",
    surface: "magic",
    api: "$wakelock · $idle",
    summary: "Wake Lock and Idle Detection for presentations and session-aware UI.",
    readmePath: "packages/attention/README.md",
    tier: "advanced",
    order: 6,
    badges: ["browser-only"],
    related: ["permissions"],
    requires: ["permissions"],
    demo: { available: true, componentId: "attention" },
    docs: { available: true },
  }),
  entry({
    id: "gesture",
    title: "Gesture",
    npmPackage: "@ailuracode/alpine-gesture",
    folder: "gesture",
    category: "interaction-primitives",
    role: "feature",
    surface: "store",
    api: "$store.gesture / x-gesture",
    summary: "Headless pointer gesture recognition — tap, swipe, pan, pinch, and long-press.",
    readmePath: "packages/gesture/README.md",
    tier: "extended",
    order: 2,
    demo: { available: true, componentId: "gesture" },
    docs: { available: true },
  }),
  entry({
    id: "dialog",
    title: "Dialog",
    npmPackage: "@ailuracode/alpine-dialog",
    folder: "dialog",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.dialog",
    summary: "Accessible modal state with focus trap, scroll-lock hooks, and ARIA helpers.",
    readmePath: "packages/dialog/README.md",
    tier: "headless",
    order: 1,
    related: ["overlay", "scroll"],
    demo: { available: true, componentId: "dialog" },
    docs: { available: true },
  }),
  entry({
    id: "menu",
    title: "Menu",
    npmPackage: "@ailuracode/alpine-menu",
    folder: "menu",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.menu",
    summary: "Dropdown and context menu state with keyboard navigation and ARIA helpers.",
    readmePath: "packages/menu/README.md",
    tier: "headless",
    order: 2,
    related: ["overlay"],
    demo: { available: true, componentId: "menu" },
    docs: { available: true },
  }),
  entry({
    id: "tooltip",
    title: "Tooltip",
    npmPackage: "@ailuracode/alpine-tooltip",
    folder: "tooltip",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.tooltip",
    summary: "Tooltip open/close state with hover and focus delays.",
    readmePath: "packages/tooltip/README.md",
    tier: "headless",
    order: 3,
    related: ["overlay"],
    demo: { available: true, componentId: "tooltip" },
    docs: { available: true },
  }),
  entry({
    id: "toast",
    title: "Toast",
    npmPackage: "@ailuracode/alpine-toast",
    folder: "toast",
    category: "headless-ui",
    role: "feature",
    surface: "magic",
    api: "$toast",
    summary: "Headless toast queue with timed and persistent stacks.",
    readmePath: "packages/toast/README.md",
    tier: "headless",
    order: 4,
    related: ["notify"],
    demo: { available: true, componentId: "toast" },
    docs: { available: true },
  }),
  entry({
    id: "tabs",
    title: "Tabs",
    npmPackage: "@ailuracode/alpine-tabs",
    folder: "tabs",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.tabs",
    summary: "Accessible tabs with keyboard navigation and optional URL query sync.",
    readmePath: "packages/tabs/README.md",
    tier: "headless",
    order: 5,
    demo: { available: true, componentId: "tabs" },
    docs: { available: true },
  }),
  entry({
    id: "accordion",
    title: "Accordion",
    npmPackage: "@ailuracode/alpine-accordion",
    folder: "accordion",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.accordion",
    summary: "Single or multi-open accordion state with keyboard focus and ARIA helpers.",
    readmePath: "packages/accordion/README.md",
    tier: "headless",
    order: 6,
    demo: { available: true, componentId: "accordion" },
    docs: { available: true },
  }),
  entry({
    id: "command",
    title: "Command",
    npmPackage: "@ailuracode/alpine-command",
    folder: "command",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.command",
    summary: "Spotlight-style command palette with searchable actions and shortcuts.",
    readmePath: "packages/command/README.md",
    tier: "headless",
    order: 7,
    related: ["overlay", "keyboard"],
    demo: { available: true, componentId: "command" },
    docs: { available: true },
  }),
  entry({
    id: "carousel",
    title: "Carousel",
    npmPackage: "@ailuracode/alpine-carousel",
    folder: "carousel",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.carousel",
    summary: "Accessible carousel store powered by Embla.",
    readmePath: "packages/carousel/README.md",
    tier: "headless",
    order: 8,
    demo: { available: true, componentId: "carousel" },
    docs: { available: true },
  }),
  entry({
    id: "virtual",
    title: "Virtual",
    npmPackage: "@ailuracode/alpine-virtual",
    folder: "virtual",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.virtual / $virtual",
    summary: "Headless virtual list controller with fixed and variable item sizes.",
    readmePath: "packages/virtual/README.md",
    tier: "headless",
    order: 9,
    demo: { available: true, componentId: "virtual" },
    docs: { available: true },
  }),
  entry({
    id: "selection",
    title: "Selection",
    npmPackage: "@ailuracode/alpine-selection",
    folder: "selection",
    category: "headless-ui",
    role: "feature",
    surface: "store",
    api: "$store.selection / $selection",
    summary: "Framework-agnostic selection primitives with single, multiple, and range modes.",
    readmePath: "packages/selection/README.md",
    tier: "headless",
    order: 10,
    related: ["calendar"],
    demo: { available: true, componentId: "selection" },
    docs: { available: true },
  }),
  entry({
    id: "query",
    title: "Query",
    npmPackage: "@ailuracode/alpine-query",
    folder: "query",
    category: "data-networking",
    family: "query-stack",
    role: "foundation",
    surface: "core",
    api: "createQueryClient · query({ adapter })",
    summary: "Store-agnostic query cache with pluggable reactivity adapters.",
    readmePath: "packages/query/README.md",
    tier: "advanced",
    order: 1,
    badges: ["infrastructure"],
    related: ["query-kit", "query-adapter-alpine", "query-adapter-zustand"],
    demo: { available: true, componentId: "query" },
    docs: { available: true, routeId: "query" },
  }),
  entry({
    id: "query-adapter-alpine",
    title: "Query adapter (Alpine)",
    npmPackage: "@ailuracode/alpine-query-adapter-alpine",
    folder: "query-adapter-alpine",
    category: "data-networking",
    family: "query-stack",
    role: "adapter",
    surface: "core",
    api: "alpineQueryAdapter",
    summary: "Native Alpine.reactive adapter for the query cache.",
    readmePath: "packages/query-adapter-alpine/README.md",
    tier: "advanced",
    order: 2,
    badges: ["adapter"],
    related: ["query", "query-kit"],
    requires: ["query"],
    docs: { available: false },
  }),
  entry({
    id: "query-adapter-zustand",
    title: "Query adapter (Zustand)",
    npmPackage: "@ailuracode/alpine-query-adapter-zustand",
    folder: "query-adapter-zustand",
    category: "data-networking",
    family: "query-stack",
    role: "adapter",
    surface: "core",
    api: "zustandQueryAdapter",
    summary: "Zustand vanilla adapter bridged to Alpine.reactive.",
    readmePath: "packages/query-adapter-zustand/README.md",
    tier: "advanced",
    order: 3,
    badges: ["adapter"],
    related: ["query", "query-kit"],
    requires: ["query"],
    docs: { available: false },
  }),
  entry({
    id: "query-kit",
    title: "Query kit",
    npmPackage: "@ailuracode/alpine-query-kit",
    folder: "query-kit",
    category: "data-networking",
    family: "query-stack",
    role: "bundle",
    surface: "core",
    api: "$store.query · devtools",
    summary: "Recommended query stack: cache, Nanostores adapter, and optional devtools panel.",
    readmePath: "packages/query-kit/README.md",
    tier: "advanced",
    order: 4,
    badges: ["recommended", "bundle"],
    related: ["query", "query-adapter-alpine", "query-adapter-zustand"],
    requires: ["query"],
    demo: { available: true, componentId: "query-kit" },
    docs: { available: true },
  }),
  entry({
    id: "calendar",
    title: "Calendar",
    npmPackage: "@ailuracode/alpine-calendar",
    folder: "calendar",
    category: "data-networking",
    role: "feature",
    surface: "magic",
    api: "$calendar",
    summary: "Locale-aware month grids, navigation, and date selection.",
    readmePath: "packages/calendar/README.md",
    tier: "advanced",
    order: 5,
    related: ["selection"],
    demo: { available: true, componentId: "calendar" },
    docs: { available: true },
  }),
  entry({
    id: "json-api",
    title: "JSON:API",
    npmPackage: "@ailuracode/alpine-json-api",
    folder: "json-api",
    category: "data-networking",
    role: "feature",
    surface: "magic",
    api: "$jsonapi",
    summary: "Typed JSON:API client with resource schemas and compound document parsing.",
    readmePath: "packages/json-api/README.md",
    tier: "advanced",
    order: 6,
    related: ["query"],
    demo: { available: true, componentId: "json-api" },
    docs: { available: true },
  }),
] as const;
